const GET_ALL_STOCKS= 'GET_ALL_STOCKS';
const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS'
const GET_STOCKS_ERROR = 'GET_STOCKS_ERROR'
const ALL_USERS = "ALL_USERS";
const LOGIN_USER = "LOGIN_USER";
const LOGIN_CLIENT = "LOGIN_CLIENT"
const LOADING = "LOADING";

export {
    GET_ALL_STOCKS,
    GET_STOCKS_SUCCESS,
    GET_STOCKS_ERROR,
    ALL_USERS,
    LOADING,   
    LOGIN_USER,
    LOGIN_CLIENT
}